server:
  port: 80
  tomcat:
      url-encoding: UTF-8

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8
        username: root
        password:
        database: MYSQL
        show-sql: true

        hibernate:
            ddl-auto: update
            naming-stratey: org.hibernate.cfg.ImprovedNamingStrategy
            properties:
                hibernate:
                    dialect: org.hibernate.dialect.MySQL5Dialect